version: '3'
services:
  db:
    image: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - clientes-compose-network
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1992
      MYSQL_DATABASE: clientes_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - clientes-compose-network
    links:
      - db
    ports:
      - 8000:80

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: cifra/clientes:1.0
    links:
      - db
    networks:
      - clientes-compose-network
    depends_on:
      - db
    ports:
      - 8081:8081

volumes:
  dbdata:

networks:
  clientes-compose-network:
    driver: bridge

